# Generated by Django 5.2.17 on 2026-10-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Django Inventory', max_length=150)),
                ('sales_order_prefix', models.CharField(default='SO', max_length=10)),
                ('purchase_order_prefix', models.CharField(default='PO', max_length=10)),
                ('default_reorder_level', models.PositiveIntegerField(default=0)),
                ('low_stock_notifications_enabled', models.BooleanField(default=True)),
                ('order_notifications_enabled', models.BooleanField(default=True)),
                ('items_per_page', models.PositiveIntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
