# Generated by Django 5.2.17 on 2026-10-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='company_description',
            field=models.CharField(default='Auto Parts Wholesale', max_length=200),
        ),
    ]
