# Generated by Django 5.2.17 on 2026-10-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_stockreservation'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_reservation_quantity_gt_0'),
        ),
    ]
