# Generated by Django 5.2.17 on 2026-10-05 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockreservation_stock_reservation_quantity_gt_0'),
        ('purchasing', '0002_purchaseorderitem_purchase_order_item_quantity_gt_0_and_more'),
        ('sales', '0002_salesorderitem_sales_order_item_quantity_gt_0_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='stock_movement_quantity_not_0'),
        ),
    ]
