# Generated by Django 5.2.17 on 2026-10-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_order_item_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='purchase_order_item_unit_price_gte_0'),
        ),
    ]
